// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://odplkhxbiihqldjjgsxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9kcGxraHhiaWlocWxkampnc3h5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NjA5MjgsImV4cCI6MjA1OTUzNjkyOH0.iiIENSbDNtNuvVPbg7BbkinSJudZ0LMUEjDzaXtGg6U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);